language: python
python:
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu trusty/'
  - sudo apt-get update
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
  - sudo apt-get install r-base  # for R interface
  - sudo apt-get install r-base-dev
  - sudo bash ./R-setup.sh
install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r travis_requirements.txt
  - python setup.py develop
script:
  - coverage run -m unittest discover -v
notifications:
  email:
    - joris.vankerschaver@gmail.com
after_success:
  coveralls
