language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -rrequirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v
notifications:
  email:
    - joris.vankerschaver@gmail.com
